name: After Release

on:
  release:
    types: [published]

jobs:
  # Core template releases update engine deps in same repo
  self-update:
    if: "!contains(github.event.release.tag_name, '/')"
    uses: gofiber/.github/.github/workflows/after-release.yml@main
    with:
      repos: |
        - gofiber/template
    secrets:
      dispatch-token: ${{ secrets.DISPATCH_TOKEN }}

  notify-dependents:
    uses: gofiber/.github/.github/workflows/after-release.yml@main
    with:
      repos: |
        - gofiber/recipes
    secrets:
      dispatch-token: ${{ secrets.DISPATCH_TOKEN }}
