name: Release Drafter Core
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            # only on the first level
            - go.mod
            - '*.go'

jobs:
    draft_release_arangodb:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v6
                with:
                    config-name: release-drafter-core.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
